name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  wheel
        python -m pip install setuptools==69.5.1
        pip install -r ./bin/requirements.txt

    - name: Run unittest
      run: python -m unittest discover -s bin/tests -p 'test_*.py'
